### ISSUE TITLE
panic when device is unplugged during operations

### ISSUE THREAD

**Issue by marshallbrekka** [marshallbrekka/go-u2fhost#2]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a6f154]

goroutine 1 [running]:
vendor/github.com/marshallbrekka/go%2ehid.(*Device).Write(0x0, 0xc4205bb770, 0x41, 0x41, 0x4, 0xc42014e001, 0xc420755fd0)
	github.com/marshallbrekka/go.hid/hid.go:364 +0x34
github.com/marshallbrekka/go-u2fhost/hid.(*RawHidDevice).Write(0xc4202c9a50, 0xc4205bb770, 0x41, 0x41, 0x5, 0x5, 0xc4205bb770)
	github.com/wearefair/fair-cli/vendor/github.com/marshallbrekka/go-u2fhost/hid/wrapper.go:36 +0x4d
github.com/marshallbrekka/go-u2fhost/hid.sendRequest(0x5493c20, 0xc4202c9a50, 0x3ffffffff, 0xc42014e120, 0x8a, 0x8a, 0x8a, 0xc42014e120)
	github.com/marshallbrekka/go-u2fhost/hid/hid.go:138 +0x357
```

**Comment by marshallbrekka** [comment]
Seems like this is something that could/should be handled at the go.hid layer, since all of the device methods can return an error.

**Comment by marshallbrekka** [comment]
This is fixed by migrating to [karalabe/hid](https://github.com/karalabe/hid/blob/master/hid_enabled.go#L164)
